name: guard
on:
  push:
  pull_request:
jobs:
  guard:
    if: >
      ${{ !contains(github.event.head_commit.message, '[skip ci]')
          && !contains(github.event.pull_request.title, '[skip ci]')
          && !contains(github.event.pull_request.body, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "CI running (no [skip ci] found)"
